[package]
name = "zero-pet"
description = "零的桌宠 · Live2D Desktop Pet"
version = "0.1.0"
authors = ["han"]
edition = "2021"
license = "MIT"
rust-version = "1.65.0"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.6", features = ["api-all", "tray-icon"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
tokio = { version = "1", features = ["macros"] }
screenshots = "0.8"
image = "0.24"
arboard = "3"
dirs = "5"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
